In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
df=pd.read_csv('C:/Users/Dell/Desktop/Interview.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 28 columns):
Date of Interview                                                                                     1233 non-null object
Client name                                                                                           1234 non-null object
Industry                                                                                              1233 non-null object
Location                                                                                              1233 non-null object
Position to be closed                                                                                 1233 non-null object
Nature of Skillset                                                                                    1233 non-null object
Interview Type                                                                                        1233 non-null object
Name(Cand ID)                   

In [3]:
df.drop(["Unnamed: 23",'Unnamed: 24','Unnamed: 25','Unnamed: 26','Unnamed: 27'],axis=1,inplace=True)
df.columns=['date','client','industry','location','closedpos','skills','type','id','gender','currloc','jobloc','venue','natloc','permit','meeting','call','no.','resume','clear','letter','expat','obsat','marit']

In [4]:
df.drop(df.index[df["date"].isnull()],axis=0,inplace=True)

In [5]:
df.date=df.date.str.replace(" ","")
df.date=df.date.str.replace(r'&\d[\d].\d\d\w\w','')
df.date=df.date.str.replace(r'&\d.\d\d\w\w','')
df.date=df.date.str.replace('/','.')
df.date=df.date.str.replace('-Apr-','.04.')
df.date=df.date.str.replace('–Apr-','.04.')
df.date=df.date.str.replace('Apr','.04.')
df.date=df.date.str.replace(r'\W16','.2016')
df.date=df.date.str.replace(r'\W15','.2015')
df.date=df.date.str.replace('-','.')
from datetime import datetime
df['date']=pd.to_datetime(df['date'],format='%d.%m.%Y')


In [6]:
df['client'].replace({'Hospira':'H','Aon Hewitt':'A','UST':'U','Standard Chartered Bank':'S','ANZ':'A1','Pfizer':'P','Standard Chartered Bank Chennai':'S','Aon hewitt Gurgaon':'A','Astrazeneca':'As','Flextronics':'F','Prodapt':'P1','Williams Lea':'W','Barclays':'B','Hewitt':'A','Woori Bank':'Wb'},inplace=True)
df['industry'].replace({'Pharmaceuticals':'P','IT Services':'I','IT Products and Services':'I','Electronics':'E','Telecom':'E','IT':'I','BFSI':'B'},inplace=True)
df.drop(df.index[df.meeting.isnull()],axis=0,inplace=True)
df.meeting.replace({'Yes':'Y','Na':'N','No':'N','yes':'Y','Not sure':'N','Not Sure':'N','cant Say':'N'},inplace=True)
df[df["permit"].isnull()]
df.drop(df.index[df.permit.isnull()],axis=0,inplace=True)
df.permit.replace({'Yes':'Y','No':'N','Not yet':'N','Yet to confirm':'N','yes':'Y','Na':'N'},inplace=True)
df.drop(df.index[df.resume.isnull()],axis=0,inplace=True)
df.obsat.replace({'No':'N','Yes':'Y','yes':'Y','no':'N','yes ':'Y','No ':'N','NO':'N','no ':'N'},inplace=True)
df['expat'].replace({'Yes':'Y','Uncertain':'N','No':'N','yes':'Y','11:00 AM':'Y','10.30 Am':'Y'},inplace=True)
df['letter'].replace({'Yes':'Y', 'Havent Checked':'N', 'No':'N', 'Need To Check':'N', 'Not sure':'N','Not Sure':'N', 'Not yet':'N', 'no':'N', 'yes':'Y', 'Na':'N'},inplace=True)
df['clear'].replace({'Yes':'Y', 'No':'N', 'No- I need to check':'N', 'yes':'Y', 'Na':'N', 'no':'N'},inplace=True)
df['resume'].replace({'Yes':'Y', 'No':'N', 'No- will take it soon':'N', 'Not yet':'N', 'yes':'Y', 'Na':'N',
       'Not Yet':'N'},inplace=True)
df['no.'].replace({'Yes':'Y', 'No':'N', 'No I have only thi number':'N', 'yes':'Y', 'Na':'N'},inplace=True)
df['call'].replace({'Yes':'Y', 'No':'N', 'No Dont':'N', 'yes':'Y', 'Na':'N'},inplace=True)
df.currloc.replace({'Chennai':'C','Gurgaon':'G','Bangalore':'B','Hyderabad':'H','Delhi':'D','chennai':'C','- Cochin- ':'K','Noida':'N','CHENNAI':'C','chennai ':'C'},inplace=True)
df.venue.replace({'Hosur':'H', 'Gurgaon':'G', 'Bangalore':'B', 'Chennai':'C', 'Hyderabad':'H',
       '- Cochin- ':'K', 'Noida':'N'},inplace=True)
df.jobloc.replace({'Hosur':'H', 'Bangalore':'B', 'Chennai':"C", 'Gurgaon':'G', 'Visakapatinam':'V',
       '- Cochin- ':'K', 'Noida':'N'},inplace=True)
df.drop('id',axis=1,inplace=True)
df['type'].replace({'Scheduled Walkin':'SW', 'Scheduled ':'S', 'Walkin':'W', 'Scheduled Walk In':'SW',
       'Walkin ':'W'},inplace=True)
df.location.replace({'Chennai':'C', 'Gurgaon':'G', 'Bangalore':'B', 'Hyderabad':'H', 'Gurgaonr':'G',
       'Delhi':'D', 'chennai':'C', '- Cochin- ':'K', 'Noida':'N', 'CHENNAI':'C', 'chennai ':'C'},inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 984 entries, 0 to 1231
Data columns (total 22 columns):
date         984 non-null datetime64[ns]
client       984 non-null object
industry     984 non-null object
location     984 non-null object
closedpos    984 non-null object
skills       984 non-null object
type         984 non-null object
gender       984 non-null object
currloc      984 non-null object
jobloc       984 non-null object
venue        984 non-null object
natloc       984 non-null object
permit       984 non-null object
meeting      984 non-null object
call         984 non-null object
no.          984 non-null object
resume       984 non-null object
clear        984 non-null object
letter       984 non-null object
expat        984 non-null object
obsat        984 non-null object
marit        984 non-null object
dtypes: datetime64[ns](1), object(21)
memory usage: 176.8+ KB


In [8]:
df1=df.drop(["date","skills","natloc"],axis=1)

## LABEL ENCODING ALL COLUMNS

In [9]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
def encode(df1,col):
    df1.loc[:,col]=le.fit_transform(df1.loc[:,col])
for i in df1.columns:
    encode(df1,i)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 984 entries, 0 to 1231
Data columns (total 19 columns):
client       984 non-null int32
industry     984 non-null int32
location     984 non-null int32
closedpos    984 non-null int32
type         984 non-null int32
gender       984 non-null int32
currloc      984 non-null int32
jobloc       984 non-null int32
venue        984 non-null int32
permit       984 non-null int32
meeting      984 non-null int32
call         984 non-null int32
no.          984 non-null int32
resume       984 non-null int32
clear        984 non-null int32
letter       984 non-null int32
expat        984 non-null int32
obsat        984 non-null int32
marit        984 non-null int32
dtypes: int32(19)
memory usage: 80.7 KB


In [11]:
for i in df1.columns:
    print (i, df1[i].unique(),sep=" ")

SyntaxError: invalid syntax (<ipython-input-11-446a5498ae9d>, line 2)

## APPLYING DECISION TREE ON FULL DATASET CONSIDERING ALL FEATURES (0.763359301148,0.738217683452)

In [12]:
X=df1.drop("obsat",axis=1)

In [13]:
y=df1["obsat"]

In [14]:
print (X.shape,y.shape)

((984, 18), (984L,))


In [15]:
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(criterion="entropy")
clf.fit(Xtrain,ytrain)
y_pred=clf.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,clf.predict(Xtrain)))
print (classification_report(ytest,y_pred))
print(confusion_matrix(ytrain,clf.predict(Xtrain)))
print(confusion_matrix(ytest,y_pred))
print(accuracy_score(ytrain,clf.predict(Xtrain)))

              precision    recall  f1-score   support

           0       0.85      0.35      0.49       231
           1       0.77      0.97      0.86       507

   micro avg       0.78      0.78      0.78       738
   macro avg       0.81      0.66      0.67       738
weighted avg       0.79      0.78      0.74       738

              precision    recall  f1-score   support

           0       0.68      0.27      0.39        77
           1       0.74      0.94      0.83       169

   micro avg       0.73      0.73      0.73       246
   macro avg       0.71      0.61      0.61       246
weighted avg       0.72      0.73      0.69       246

[[ 80 151]
 [ 14 493]]
[[ 21  56]
 [ 10 159]]
0.7764227642276422


In [16]:
from sklearn.metrics import average_precision_score
print(average_precision_score(ytest,clf.predict(Xtest)))
print(average_precision_score(ytrain,clf.predict(Xtrain)))

0.7364258296497923
0.7633593011478645


# Feature importance

In [58]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X,y)
print (pd.DataFrame(rf.feature_importances_,index=X.columns,columns=["imp"]).sort_values("imp",ascending=False))

                imp
expat      0.217204
gender     0.091710
type       0.086396
closedpos  0.080003
marit      0.076010
permit     0.065045
client     0.063092
industry   0.060457
letter     0.049309
no.        0.035424
currloc    0.031355
meeting    0.028297
resume     0.027056
jobloc     0.024255
clear      0.020872
location   0.019775
venue      0.014632
call       0.009108


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


#  Applying decision Tree on full dataset selecting first 10 features(0.760818859265,0.743314159262)

In [83]:
X=df1[["expat","type","gender","client","letter","resume","marit","closedpos","permit","industry"]]
y=df1["obsat"]
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(criterion="entropy")
clf.fit(Xtrain,ytrain)
y_pred=clf.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,clf.predict(Xtrain)))
print (classification_report(ytest,y_pred))
print(confusion_matrix(ytrain,clf.predict(Xtrain)))
print(confusion_matrix(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.35      0.48       231
           1       0.76      0.96      0.85       507

   micro avg       0.77      0.77      0.77       738
   macro avg       0.79      0.65      0.67       738
weighted avg       0.78      0.77      0.74       738

              precision    recall  f1-score   support

           0       0.67      0.31      0.42        77
           1       0.75      0.93      0.83       169

   micro avg       0.74      0.74      0.74       246
   macro avg       0.71      0.62      0.63       246
weighted avg       0.72      0.74      0.70       246

[[ 80 151]
 [ 19 488]]
[[ 24  53]
 [ 12 157]]


In [84]:
from sklearn.metrics import average_precision_score
print(average_precision_score(ytest,clf.predict(Xtest)))
print(average_precision_score(ytrain,clf.predict(Xtrain)))

0.743314159262
0.760818859265


# DecisionTree by balancing dataset and selecting first 10 features(0.675835216314,0.721488955072)

In [90]:
c_1=0
c_0=0
Xtrain=df1.copy(deep=True)
print (Xtrain.shape)

(984, 19)


In [91]:
for i,series in df1.iterrows():
    if series["obsat"]==1:
        if c_1<320:
            c_1+=1
        else:
            Xtrain.drop(i,axis=0,inplace=True)
    else:
        if c_0<308:
            c_0+=1
        else:
            Xtrain.drop(i,axis=0,inplace=True)


In [92]:
A,Xtest,B,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
print(Xtest.shape,ytest.shape)

(246, 10) (246,)


In [93]:
ytrain=Xtrain["obsat"]
Xtrain.drop("obsat",axis=1,inplace=True)
XTrain=Xtrain[["expat","type","gender","client","letter","resume","marit","closedpos","permit","industry"]]
print (XTrain.shape,ytrain.shape,Xtest.shape,ytest.shape)

(628, 10) (628,) (246, 10) (246,)


In [94]:
clf.fit(XTrain,ytrain)
y_pred=clf.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,clf.predict(XTrain)))
print (classification_report(ytest,y_pred))
print(confusion_matrix(ytrain,clf.predict(XTrain)))
print(confusion_matrix(ytest,y_pred))
print(average_precision_score(ytest,clf.predict(Xtest)))
print(average_precision_score(ytrain,clf.predict(XTrain)))

              precision    recall  f1-score   support

           0       0.69      0.78      0.73       308
           1       0.76      0.67      0.71       320

   micro avg       0.72      0.72      0.72       628
   macro avg       0.73      0.72      0.72       628
weighted avg       0.73      0.72      0.72       628

              precision    recall  f1-score   support

           0       0.36      0.74      0.49        77
           1       0.77      0.40      0.53       169

   micro avg       0.51      0.51      0.51       246
   macro avg       0.57      0.57      0.51       246
weighted avg       0.64      0.51      0.52       246

[[239  69]
 [105 215]]
[[ 57  20]
 [101  68]]
0.721488955072
0.675835216314


# RandomForest on full dataset 10 best features(0.758259959021,0.746637286876)


In [98]:
X=df1[["expat","type","gender","client","letter","resume","marit","closedpos","permit","industry"]]
y=df1["obsat"]
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(criterion="entropy")
clf.fit(Xtrain,ytrain)
y_pred=clf.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,clf.predict(Xtrain)))
print (classification_report(ytest,y_pred))
print(confusion_matrix(ytrain,clf.predict(Xtrain)))
print(confusion_matrix(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.33      0.47       231
           1       0.76      0.97      0.85       507

   micro avg       0.77      0.77      0.77       738
   macro avg       0.80      0.65      0.66       738
weighted avg       0.78      0.77      0.73       738

              precision    recall  f1-score   support

           0       0.66      0.30      0.41        77
           1       0.74      0.93      0.83       169

   micro avg       0.73      0.73      0.73       246
   macro avg       0.70      0.61      0.62       246
weighted avg       0.72      0.73      0.70       246

[[ 76 155]
 [ 15 492]]
[[ 23  54]
 [ 12 157]]


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [99]:
print(average_precision_score(ytest,clf.predict(Xtest)))
print(average_precision_score(ytrain,clf.predict(Xtrain)))

0.740022530487
0.758259959021


# RandomForest on balanced dataset selecting 10 features(0.675835216314,0.721488955072)

In [97]:
c_1=0
c_0=0
Xtrain=df1.copy(deep=True)
for i,series in df1.iterrows():
    if series["obsat"]==1:
        if c_1<320:
            c_1+=1
        else:
            Xtrain.drop(i,axis=0,inplace=True)
    else:
        if c_0<308:
            c_0+=1
        else:
            Xtrain.drop(i,axis=0,inplace=True)
A,Xtest,B,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
ytrain=Xtrain["obsat"]
Xtrain.drop("obsat",axis=1,inplace=True)
XTrain=Xtrain[["expat","type","gender","client","letter","resume","marit","closedpos","permit","industry"]]
clf.fit(XTrain,ytrain)
y_pred=clf.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,clf.predict(XTrain)))
print (classification_report(ytest,y_pred))
print(confusion_matrix(ytrain,clf.predict(XTrain)))
print(confusion_matrix(ytest,y_pred))
print(average_precision_score(ytest,clf.predict(Xtest)))
print(average_precision_score(ytrain,clf.predict(XTrain)))


              precision    recall  f1-score   support

           0       0.69      0.78      0.73       308
           1       0.76      0.67      0.71       320

   micro avg       0.72      0.72      0.72       628
   macro avg       0.73      0.72      0.72       628
weighted avg       0.73      0.72      0.72       628

              precision    recall  f1-score   support

           0       0.36      0.74      0.49        77
           1       0.77      0.40      0.53       169

   micro avg       0.51      0.51      0.51       246
   macro avg       0.57      0.57      0.51       246
weighted avg       0.64      0.51      0.52       246

[[239  69]
 [105 215]]
[[ 57  20]
 [101  68]]
0.721488955072
0.675835216314
