In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
df=pd.read_csv('C:/Users/Dell/Desktop/Interview.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 28 columns):
Date of Interview                                                                                     1233 non-null object
Client name                                                                                           1234 non-null object
Industry                                                                                              1233 non-null object
Location                                                                                              1233 non-null object
Position to be closed                                                                                 1233 non-null object
Nature of Skillset                                                                                    1233 non-null object
Interview Type                                                                                        1233 non-null object
Name(Cand ID)                   

In [3]:
df.drop(["Unnamed: 23",'Unnamed: 24','Unnamed: 25','Unnamed: 26','Unnamed: 27'],axis=1,inplace=True)
df.columns=['date','client','industry','location','closedpos','skills','type','id','gender','currloc','jobloc','venue','natloc','permit','meeting','call','no.','resume','clear','letter','expat','obsat','marit']


In [4]:
df.drop(df.index[df["date"].isnull()],axis=0,inplace=True)

In [5]:
df.date=df.date.str.replace(" ","")
df.date=df.date.str.replace(r'&\d[\d].\d\d\w\w','')
df.date=df.date.str.replace(r'&\d.\d\d\w\w','')
df.date=df.date.str.replace('/','.')
df.date=df.date.str.replace('-Apr-','.04.')
df.date=df.date.str.replace('–Apr-','.04.')
df.date=df.date.str.replace('Apr','.04.')
df.date=df.date.str.replace(r'\W16','.2016')
df.date=df.date.str.replace(r'\W15','.2015')
df.date=df.date.str.replace('-','.')


In [6]:
from datetime import datetime
df['date']=pd.to_datetime(df['date'],format='%d.%m.%Y')
df["date"]=df["date"].dt.date

In [7]:
df.date.unique()

array([datetime.date(2015, 2, 13), datetime.date(2015, 6, 19),
       datetime.date(2015, 6, 23), datetime.date(2015, 6, 29),
       datetime.date(2015, 6, 25), datetime.date(2016, 5, 25),
       datetime.date(2016, 12, 4), datetime.date(2016, 4, 13),
       datetime.date(2016, 2, 27), datetime.date(2016, 5, 7),
       datetime.date(2016, 5, 5), datetime.date(2016, 5, 4),
       datetime.date(2016, 4, 21), datetime.date(2016, 4, 22),
       datetime.date(2016, 4, 23), datetime.date(2016, 4, 15),
       datetime.date(2016, 4, 19), datetime.date(2016, 4, 20),
       datetime.date(2016, 4, 25), datetime.date(2016, 4, 18),
       datetime.date(2016, 5, 11), datetime.date(2016, 5, 10),
       datetime.date(2016, 4, 12), datetime.date(2017, 4, 12),
       datetime.date(2018, 4, 12), datetime.date(2019, 4, 12),
       datetime.date(2020, 4, 12), datetime.date(2021, 4, 12),
       datetime.date(2022, 4, 12), datetime.date(2023, 4, 12),
       datetime.date(2016, 5, 8), datetime.date(2016, 3, 1

In [8]:
df['client'].replace({'Hospira':'H','Aon Hewitt':'A','UST':'U','Standard Chartered Bank':'S','ANZ':'A1','Pfizer':'P','Standard Chartered Bank Chennai':'S','Aon hewitt Gurgaon':'A','Astrazeneca':'As','Flextronics':'F','Prodapt':'P1','Williams Lea':'W','Barclays':'B','Hewitt':'A','Woori Bank':'Wb'},inplace=True)

In [9]:
df['industry'].replace({'Pharmaceuticals':'P','IT Services':'I','IT Products and Services':'I','Electronics':'E','Telecom':'E','IT':'I','BFSI':'B'},inplace=True)

In [10]:
df.drop(df.index[df.meeting.isnull()],axis=0,inplace=True)

In [11]:
df.meeting.replace({'Yes':'Y','Na':'N','No':'N','yes':'Y','Not sure':'N','Not Sure':'N','cant Say':'N'},inplace=True)

In [12]:
df.drop(df.index[df.permit.isnull()],axis=0,inplace=True)

In [13]:
df.permit.replace({'Yes':'Y','No':'N','Not yet':'N','Yet to confirm':'N','yes':'Y','Na':'N'},inplace=True)

In [14]:
df.drop(df.index[df.resume.isnull()],axis=0,inplace=True)

In [15]:
df.obsat.replace({'No':'N','Yes':'Y','yes':'Y','no':'N','yes ':'Y','No ':'N','NO':'N','no ':'N'},inplace=True)

In [16]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df.loc[:,'obsat']=le.fit_transform(df.loc[:,'obsat'])

In [17]:
df['expat'].replace({'Yes':'Y','Uncertain':'N','No':'N','yes':'Y','11:00 AM':'Y','10.30 Am':'Y'},inplace=True)
df['expat']=le.fit_transform(df['expat'])

In [18]:
df['letter'].replace({'Yes':'Y', 'Havent Checked':'N', 'No':'N', 'Need To Check':'N', 'Not sure':'N','Not Sure':'N', 'Not yet':'N', 'no':'N', 'yes':'Y', 'Na':'N'},inplace=True)

In [19]:
df['clear'].replace({'Yes':'Y', 'No':'N', 'No- I need to check':'N', 'yes':'Y', 'Na':'N', 'no':'N'},inplace=True)

In [20]:
df['resume'].replace({'Yes':'Y', 'No':'N', 'No- will take it soon':'N', 'Not yet':'N', 'yes':'Y', 'Na':'N',
       'Not Yet':'N'},inplace=True)

In [21]:
df['no.'].replace({'Yes':'Y', 'No':'N', 'No I have only thi number':'N', 'yes':'Y', 'Na':'N'},inplace=True)

In [22]:
df['call'].replace({'Yes':'Y', 'No':'N', 'No Dont':'N', 'yes':'Y', 'Na':'N'},inplace=True)

In [23]:
df.currloc.replace({'Chennai':'C','Gurgaon':'G','Bangalore':'B','Hyderabad':'H','Delhi':'D','chennai':'C','- Cochin- ':'K','Noida':'N','CHENNAI':'C','chennai ':'C'},inplace=True)

In [24]:
df.venue.replace({'Hosur':'H', 'Gurgaon':'G', 'Bangalore':'B', 'Chennai':'C', 'Hyderabad':'H',
       '- Cochin- ':'K', 'Noida':'N'},inplace=True)

In [25]:
df.jobloc.replace({'Hosur':'H', 'Bangalore':'B', 'Chennai':"C", 'Gurgaon':'G', 'Visakapatinam':'V',
       '- Cochin- ':'K', 'Noida':'N'},inplace=True)

In [26]:
df['type'].replace({'Scheduled Walkin':'SW', 'Scheduled ':'S', 'Walkin':'W', 'Scheduled Walk In':'SW',
       'Walkin ':'W'},inplace=True)

In [27]:
df.location.replace({'Chennai':'C', 'Gurgaon':'G', 'Bangalore':'B', 'Hyderabad':'H', 'Gurgaonr':'G',
       'Delhi':'D', 'chennai':'C', '- Cochin- ':'K', 'Noida':'N', 'CHENNAI':'C', 'chennai ':'C'},inplace=True)

In [28]:
df.closedpos.replace({'Production- Sterile':'P','Selenium testing':'S','Dot Net':'D','AML':'A','Trade Finance':'T','Routine':'R','Niche':'N'},inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 984 entries, 0 to 1231
Data columns (total 23 columns):
date         984 non-null object
client       984 non-null object
industry     984 non-null object
location     984 non-null object
closedpos    984 non-null object
skills       984 non-null object
type         984 non-null object
id           984 non-null object
gender       984 non-null object
currloc      984 non-null object
jobloc       984 non-null object
venue        984 non-null object
natloc       984 non-null object
permit       984 non-null object
meeting      984 non-null object
call         984 non-null object
no.          984 non-null object
resume       984 non-null object
clear        984 non-null object
letter       984 non-null object
expat        984 non-null int32
obsat        984 non-null int32
marit        984 non-null object
dtypes: int32(2), object(21)
memory usage: 176.8+ KB


In [30]:
df.head()

date client industry location closedpos   skills type           id  \
0  2015-02-13      H        P        C         P  Routine   SW  Candidate 1   
1  2015-02-13      H        P        C         P  Routine   SW  Candidate 2   
3  2015-02-13      H        P        C         P  Routine   SW  Candidate 4   
4  2015-02-13      H        P        C         P  Routine   SW  Candidate 5   
5  2015-02-13      A        I        G         S  Routine   SW  Candidate 6   

  gender currloc   ...    permit meeting call no. resume clear letter expat  \
0   Male       C   ...         Y       Y    Y   Y      Y     Y      Y     1   
1   Male       C   ...         Y       Y    Y   Y      Y     Y      Y     1   
3   Male       C   ...         Y       Y    N   Y      N     Y      Y     0   
4   Male       C   ...         Y       Y    Y   N      Y     Y      Y     0   
5   Male       G   ...         Y       Y    Y   Y      Y     Y      Y     1   

  obsat    marit  
0     0   Single  
1     0   Single  
3     0   Single  
4     0  Married  
5     1   Single  

[5 rows x 23 columns]

In [31]:
df.drop("id",axis=1,inplace=True)

In [32]:
df.head()

date client industry location closedpos   skills type gender currloc  \
0  2015-02-13      H        P        C         P  Routine   SW   Male       C   
1  2015-02-13      H        P        C         P  Routine   SW   Male       C   
3  2015-02-13      H        P        C         P  Routine   SW   Male       C   
4  2015-02-13      H        P        C         P  Routine   SW   Male       C   
5  2015-02-13      A        I        G         S  Routine   SW   Male       G   

  jobloc   ...    permit meeting call no. resume clear letter expat obsat  \
0      H   ...         Y       Y    Y   Y      Y     Y      Y     1     0   
1      B   ...         Y       Y    Y   Y      Y     Y      Y     1     0   
3      C   ...         Y       Y    N   Y      N     Y      Y     0     0   
4      B   ...         Y       Y    Y   N      Y     Y      Y     0     0   
5      G   ...         Y       Y    Y   Y      Y     Y      Y     1     1   

     marit  
0   Single  
1   Single  
3   Single  
4  Married  
5   Single  

[5 rows x 22 columns]

In [33]:
df.columns

Index([u'date', u'client', u'industry', u'location', u'closedpos', u'skills',
       u'type', u'gender', u'currloc', u'jobloc', u'venue', u'natloc',
       u'permit', u'meeting', u'call', u'no.', u'resume', u'clear', u'letter',
       u'expat', u'obsat', u'marit'],
      dtype='object')

In [114]:
for col in["date","client",'industry','location','closedpos','type','gender','currloc','jobloc','venue','permit','marit','letter','clear','resume','no.','meeting','call']:
    x=df[col].unique()
    cn=dict()
    cn1=dict()
    cn2=dict()   
    for i in x:
        cn[i]=df[df[col]==i].shape[0]
        cn1[i]=df[(df[col]==i) & (df.expat==1)].shape[0]
        cn2[i]=df[(df[col]==i) & (df.expat==0)].shape[0]
    a=col+"_T"
    b=col+"_N"
    df[a]=0
    df[b]=0
    for i,series in df.iterrows():
        if(series.expat==1):
            df.loc[i,a]=cn1[series[col]]/cn[series[col]]
        else:
            df.loc[i,b]=cn2[series[col]]/cn[series[col]]
    df.drop(col,axis=1,inplace=True)

KeyError: 'date'

In [115]:
df.head()

skills   natloc  expat  obsat  date_T  date_N  client_T  client_N  \
0  Routine    Hosur      1      0       0       0         0         0   
1  Routine   Trichy      1      0       0       0         0         0   
3  Routine  Chennai      0      0       0       0         0         0   
4  Routine  Chennai      0      0       0       0         0         0   
5  Routine  Gurgaon      1      1       0       0         0         0   

   industry_T  industry_N   ...    clear_T  clear_N  resume_T  resume_N  \
0           0           0   ...          0        0         0         0   
1           0           0   ...          0        0         0         0   
3           0           0   ...          0        0         0         1   
4           0           0   ...          0        0         0         0   
5           0           0   ...          0        0         0         0   

   no._T  no._N  meeting_T  meeting_N  call_T  call_N  
0      0      0          0          0       0       0  
1      0      0          0          0       0       0  
3      0      0          0          0       0       1  
4      0      1          0          0       0       0  
5      0      0          0          0       0       0  

[5 rows x 40 columns]

In [116]:
X=df.drop("skills",axis=1)
X.drop("natloc",axis=1,inplace=True)

In [117]:
X.drop("expat",axis=1,inplace=True)
X.drop("obsat",axis=1,inplace=True)

In [41]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 984 entries, 0 to 1231
Data columns (total 36 columns):
date_T         984 non-null float64
date_N         984 non-null float64
client_T       984 non-null float64
client_N       984 non-null float64
industry_T     984 non-null float64
industry_N     984 non-null float64
location_T     984 non-null float64
location_N     984 non-null float64
closedpos_T    984 non-null float64
closedpos_N    984 non-null float64
type_T         984 non-null float64
type_N         984 non-null float64
gender_T       984 non-null float64
gender_N       984 non-null float64
currloc_T      984 non-null float64
currloc_N      984 non-null float64
jobloc_T       984 non-null float64
jobloc_N       984 non-null float64
venue_T        984 non-null float64
venue_N        984 non-null float64
permit_T       984 non-null float64
permit_N       984 non-null float64
marit_T        984 non-null float64
marit_N        984 non-null float64
letter_T       984 non-null fl

In [42]:
y=df["obsat"]

In [43]:
from sklearn import preprocessing
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(criterion="entropy")
rfc.fit(Xtrain,ytrain)
prediction=rfc.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,rfc.predict(Xtrain)))
print (classification_report(ytest,prediction))
print(confusion_matrix(ytrain,rfc.predict(Xtrain)))
print(confusion_matrix(ytest,rfc.predict(Xtest)))
print(accuracy_score(ytest,prediction))

              precision    recall  f1-score   support

           0       0.77      0.45      0.57       231
           1       0.79      0.94      0.86       507

   micro avg       0.79      0.79      0.79       738
   macro avg       0.78      0.69      0.71       738
weighted avg       0.78      0.79      0.77       738

              precision    recall  f1-score   support

           0       0.48      0.35      0.41        77
           1       0.74      0.83      0.78       169

   micro avg       0.68      0.68      0.68       246
   macro avg       0.61      0.59      0.59       246
weighted avg       0.66      0.68      0.66       246

[[103 128]
 [ 30 477]]
[[ 27  50]
 [ 29 140]]
0.678861788618


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [44]:
importances = rfc.feature_importances_
std = np.std([tree.feature_importances_ for tree in rfc.estimators_],axis=0)
indices = np.argsort(importances)[::-1]
print("Feature ranking:")

for f in range(X.shape[1]):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

Feature ranking:
1. feature 0 (0.219401)
2. feature 8 (0.098518)
3. feature 12 (0.084607)
4. feature 10 (0.073796)
5. feature 2 (0.057172)
6. feature 22 (0.047474)
7. feature 21 (0.041801)
8. feature 14 (0.034068)
9. feature 4 (0.033764)
10. feature 3 (0.029461)
11. feature 1 (0.028060)
12. feature 33 (0.026667)
13. feature 7 (0.021138)
14. feature 18 (0.020846)
15. feature 16 (0.020067)
16. feature 15 (0.019988)
17. feature 28 (0.016669)
18. feature 35 (0.015919)
19. feature 11 (0.014939)
20. feature 6 (0.014045)
21. feature 29 (0.011439)
22. feature 25 (0.011386)
23. feature 31 (0.010966)
24. feature 23 (0.009939)
25. feature 20 (0.009058)
26. feature 9 (0.005941)
27. feature 13 (0.005492)
28. feature 27 (0.005413)
29. feature 5 (0.004987)
30. feature 19 (0.004300)
31. feature 17 (0.002150)
32. feature 26 (0.000528)
33. feature 30 (0.000000)
34. feature 24 (0.000000)
35. feature 32 (0.000000)
36. feature 34 (0.000000)


In [45]:
from sklearn.metrics import average_precision_score
average_precision_score(ytest,rfc.predict(Xtest))

0.72828792286677146

In [46]:
average_precision_score(ytrain,rfc.predict(Xtrain))

0.78242751051893122

In [47]:
X.columns

Index(['date_T', 'date_N', 'client_T', 'client_N', 'industry_T', 'industry_N',
       'location_T', 'location_N', 'closedpos_T', 'closedpos_N', 'type_T',
       'type_N', 'gender_T', 'gender_N', 'currloc_T', 'currloc_N', 'jobloc_T',
       'jobloc_N', 'venue_T', 'venue_N', 'permit_T', 'permit_N', 'marit_T',
       'marit_N', 'letter_T', 'letter_N', 'clear_T', 'clear_N', 'resume_T',
       'resume_N', 'no._T', 'no._N', 'meeting_T', 'meeting_N', 'call_T',
       'call_N'],
      dtype='object')

# RandomForest(0.75,0.90018)

In [53]:
X=df[["date_T","closedpos_T","gender_T","type_T","marit_T"]]
y=df["obsat"]

In [54]:
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(criterion="entropy")
rfc.fit(Xtrain,ytrain)
prediction=rfc.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,rfc.predict(Xtrain)))
print (classification_report(ytest,prediction))
print(confusion_matrix(ytrain,rfc.predict(Xtrain)))
print(confusion_matrix(ytest,rfc.predict(Xtest)))
print(accuracy_score(ytest,prediction))

              precision    recall  f1-score   support

           0       0.75      0.39      0.51       231
           1       0.77      0.94      0.85       507

   micro avg       0.77      0.77      0.77       738
   macro avg       0.76      0.67      0.68       738
weighted avg       0.77      0.77      0.74       738

              precision    recall  f1-score   support

           0       0.49      0.38      0.43        77
           1       0.74      0.82      0.78       169

   micro avg       0.68      0.68      0.68       246
   macro avg       0.62      0.60      0.60       246
weighted avg       0.66      0.68      0.67       246

[[ 90 141]
 [ 30 477]]
[[ 29  48]
 [ 30 139]]
0.682926829268


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [55]:
average_precision_score(ytest,rfc.predict(Xtest))

0.73331722906824992

In [56]:
average_precision_score(ytrain,rfc.predict(Xtrain))

0.76682378502994542

# GaussianNB (0.75,0.68)

In [ ]:
X=df[["date_T","closedpos_T","gender_T","type_T","marit_T"]]
y=df["obsat"]
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
gnb.fit(Xtrain,ytrain)


In [ ]:
print (classification_report(ytrain,gnb.predict(Xtrain)))
print (classification_report(ytest,gnb.predict(Xtest)))
print(confusion_matrix(ytrain,gnb.predict(Xtrain)))
print(confusion_matrix(ytest,gnb.predict(Xtest)))
print(accuracy_score(ytest,gnb.predict(Xtest)))

In [ ]:
average_precision_score(ytest,gnb.predict_proba(Xtest)[:,1])

In [ ]:
average_precision_score(ytrain,gnb.predict_proba(Xtrain)[:,1])

# DecisionTree (0.7731,0.905)

In [ ]:
X=df[["date_T","closedpos_T","gender_T","type_T","marit_T"]]
y=df["obsat"]
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(criterion="entropy")
clf.fit(Xtrain,ytrain)
y_pred=clf.predict(Xtest)

In [ ]:
print (classification_report(ytrain,clf.predict(Xtrain)))
print (classification_report(ytest,y_pred))
print(confusion_matrix(ytrain,clf.predict(Xtrain)))
print(confusion_matrix(ytest,y_pred))
print(accuracy_score(ytest,y_pred))

In [ ]:
average_precision_score(ytest,clf.predict_proba(Xtest)[:,1])

In [ ]:
average_precision_score(ytrain,clf.predict_proba(Xtrain)[:,1])

# KNN

In [ ]:
from sklearn import neighbors
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.15,random_state=42)
model=neighbors.KNeighborsRegressor(n_neighbors=11)
model.fit(Xtrain,ytrain)
prediction=model.predict(Xtest)

In [ ]:
print (classification_report(ytrain,model.predict(Xtrain)))
print (classification_report(ytest,prediction))
print(confusion_matrix(ytrain,model.predict(Xtrain)))
print(confusion_matrix(ytest,prediction))
print(accuracy_score(ytest,prediction))

In [ ]:
from sklearn import metrics
np.sqrt(metrics.mean_squared_error(ytest,prediction))

In [ ]:
average_precision_score(ytest,model.predict_proba(Xtest)[:,1])

In [36]:
df["industry"].value_counts()

KeyError: 'industry'

In [37]:
importances = rfc.feature_importances_
std = np.std([tree.feature_importances_ for tree in rfc.estimators_],axis=0)
indices = np.argsort(importances)[::-1]
print("Feature ranking:")

for f in range(X.shape[1]):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

NameError: name 'rfc' is not defined

In [1]:
X.head()

NameError: name 'X' is not defined

# XGBoost on balanced data 10 features(0.5035526315789474,0.6906961081445134)


In [148]:
for col in ["client",'industry','location','expat','closedpos','type','gender','currloc','jobloc','venue','permit','marit','letter','clear','resume','no.','meeting','call']:
    x=df[col].unique()
    cn=dict()
    cn1=dict()
    cn2=dict()   
    for i in x:
        cn[i]=df[df[col]==i].shape[0]
        cn1[i]=df[(df[col]==i) & (df.obsat==1)].shape[0]
        cn2[i]=df[(df[col]==i) & (df.obsat==0)].shape[0]
    a=col+"_T"
    b=col+"_N"
    df[a]=0
    df[b]=0
    for i,series in df.iterrows():
        if(series.obsat==1):
            df.loc[i,a]=cn1[series[col]]/cn[series[col]]
        else:
            df.loc[i,b]=cn2[series[col]]/cn[series[col]]
    df.drop(col,axis=1,inplace=True)

In [149]:
X=df.drop("obsat",axis=1)
y=df["obsat"]
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X,y)
print (pd.DataFrame(rf.feature_importances_,index=X.columns,columns=["imp"]).sort_values("imp",ascending=False))


TypeError: float() argument must be a string or a number

In [151]:
X=df[["closedpos_T","gender_T","type_T","marit_T","obsat","client_T","resume_N","venue_T","currloc_T","client_N"]]
y=df["obsat"]
Xtrain=X.copy(deep=True)
c_1=0
c_0=0
for i,series in X.iterrows():
    if series["obsat"]==1:
        if c_1<300:
            c_1+=1
        else:
            Xtrain.drop(i,axis=0,inplace=True)
    else:
        if c_0<308:
            c_0+=1
ytrain=Xtrain["obsat"]
Xtrain.drop("obsat",axis=1,inplace=True)
X.drop("obsat",axis=1,inplace=True)

In [152]:
from sklearn import model_selection
A,Xtest,B,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
print(Xtest.shape,ytest.shape,ytrain.shape,Xtrain.shape)

((246, 9), (246L,), (608L,), (608, 9))


In [153]:
import xgboost
classifier = xgboost.XGBClassifier()
classifier.fit(Xtrain, ytrain)
y_pred=classifier.predict(Xtest)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm = confusion_matrix(ytest, y_pred)
print (cm)
print (classification_report(ytrain,classifier.predict(Xtrain)))
print (classification_report(ytest,classifier.predict(Xtest)))
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = Xtrain, y = ytrain, cv = 10)
print(accuracies.mean())
print(accuracies.std())

[[ 77   0]
 [167   2]]
              precision    recall  f1-score   support

           0       0.51      1.00      0.68       308
           1       1.00      0.02      0.04       300

   micro avg       0.52      0.52      0.52       608
   macro avg       0.76      0.51      0.36       608
weighted avg       0.75      0.52      0.36       608

              precision    recall  f1-score   support

           0       0.32      1.00      0.48        77
           1       1.00      0.01      0.02       169

   micro avg       0.32      0.32      0.32       246
   macro avg       0.66      0.51      0.25       246
weighted avg       0.79      0.32      0.17       246

0.5065573770491804
0.003278688524590168


In [154]:
from sklearn.metrics import average_precision_score
print(average_precision_score(ytest,classifier.predict(Xtest)))
print(average_precision_score(ytrain,classifier.predict(Xtrain)))

0.6906961081445134
0.5035526315789474


# XgBoost all data 10 features(1,1)

In [155]:
X=df[["closedpos_T","gender_T","type_T","marit_T","obsat","client_T","resume_N","venue_T","currloc_T","client_N"]]
y=df["obsat"]
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
print(Xtest.shape,ytest.shape,ytrain.shape,Xtrain.shape)

((246, 10), (246L,), (738L,), (738, 10))


In [156]:
import xgboost
classifier = xgboost.XGBClassifier()
classifier.fit(Xtrain, ytrain)
y_pred=classifier.predict(Xtest)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm = confusion_matrix(ytest, y_pred)
print (cm)
print (classification_report(ytrain,classifier.predict(Xtrain)))
print (classification_report(ytest,classifier.predict(Xtest)))
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = Xtrain, y = ytrain, cv = 10)
print(accuracies.mean())
print(accuracies.std())

[[ 77   0]
 [  0 169]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       231
           1       1.00      1.00      1.00       507

   micro avg       1.00      1.00      1.00       738
   macro avg       1.00      1.00      1.00       738
weighted avg       1.00      1.00      1.00       738

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        77
           1       1.00      1.00      1.00       169

   micro avg       1.00      1.00      1.00       246
   macro avg       1.00      1.00      1.00       246
weighted avg       1.00      1.00      1.00       246

1.0
0.0


In [157]:
from sklearn.metrics import average_precision_score
print(average_precision_score(ytest,classifier.predict(Xtest)))
print(average_precision_score(ytrain,classifier.predict(Xtrain)))

1.0
1.0
