In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
df=pd.read_csv('C:/Users/Dell/Desktop/Interview.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 28 columns):
Date of Interview                                                                                     1233 non-null object
Client name                                                                                           1234 non-null object
Industry                                                                                              1233 non-null object
Location                                                                                              1233 non-null object
Position to be closed                                                                                 1233 non-null object
Nature of Skillset                                                                                    1233 non-null object
Interview Type                                                                                        1233 non-null object
Name(Cand ID)                   

In [3]:
df.drop(["Unnamed: 23",'Unnamed: 24','Unnamed: 25','Unnamed: 26','Unnamed: 27'],axis=1,inplace=True)
df.columns=['date','client','industry','location','closedpos','skills','type','id','gender','currloc','jobloc','venue','natloc','permit','meeting','call','no.','resume','clear','letter','expat','obsat','marit']

In [4]:
df.drop(df.index[df["date"].isnull()],axis=0,inplace=True)

In [5]:
df.date=df.date.str.replace(" ","")
df.date=df.date.str.replace(r'&\d[\d].\d\d\w\w','')
df.date=df.date.str.replace(r'&\d.\d\d\w\w','')
df.date=df.date.str.replace('/','.')
df.date=df.date.str.replace('-Apr-','.04.')
df.date=df.date.str.replace('–Apr-','.04.')
df.date=df.date.str.replace('Apr','.04.')
df.date=df.date.str.replace(r'\W16','.2016')
df.date=df.date.str.replace(r'\W15','.2015')
df.date=df.date.str.replace('-','.')
from datetime import datetime
df['date']=pd.to_datetime(df['date'],format='%d.%m.%Y')


In [6]:
df["date"]=df["date"].dt.date

In [7]:
df['client'].replace({'Hospira':'H','Aon Hewitt':'A','UST':'U','Standard Chartered Bank':'S','ANZ':'A1','Pfizer':'P','Standard Chartered Bank Chennai':'S','Aon hewitt Gurgaon':'A','Astrazeneca':'As','Flextronics':'F','Prodapt':'P1','Williams Lea':'W','Barclays':'B','Hewitt':'A','Woori Bank':'Wb'},inplace=True)

In [8]:
df['industry'].replace({'Pharmaceuticals':'P','IT Services':'I','IT Products and Services':'I','Electronics':'E','Telecom':'E','IT':'I','BFSI':'B'},inplace=True)
df.drop(df.index[df.meeting.isnull()],axis=0,inplace=True)
df.meeting.replace({'Yes':'Y','Na':'N','No':'N','yes':'Y','Not sure':'N','Not Sure':'N','cant Say':'N'},inplace=True)
df[df["permit"].isnull()]
df.drop(df.index[df.permit.isnull()],axis=0,inplace=True)
df.permit.replace({'Yes':'Y','No':'N','Not yet':'N','Yet to confirm':'N','yes':'Y','Na':'N'},inplace=True)
df.drop(df.index[df.resume.isnull()],axis=0,inplace=True)
df.obsat.replace({'No':'N','Yes':'Y','yes':'Y','no':'N','yes ':'Y','No ':'N','NO':'N','no ':'N'},inplace=True)
df['expat'].replace({'Yes':'Y','Uncertain':'N','No':'N','yes':'Y','11:00 AM':'Y','10.30 Am':'Y'},inplace=True)
df['letter'].replace({'Yes':'Y', 'Havent Checked':'N', 'No':'N', 'Need To Check':'N', 'Not sure':'N','Not Sure':'N', 'Not yet':'N', 'no':'N', 'yes':'Y', 'Na':'N'},inplace=True)
df['clear'].replace({'Yes':'Y', 'No':'N', 'No- I need to check':'N', 'yes':'Y', 'Na':'N', 'no':'N'},inplace=True)
df['resume'].replace({'Yes':'Y', 'No':'N', 'No- will take it soon':'N', 'Not yet':'N', 'yes':'Y', 'Na':'N',
       'Not Yet':'N'},inplace=True)
df['no.'].replace({'Yes':'Y', 'No':'N', 'No I have only thi number':'N', 'yes':'Y', 'Na':'N'},inplace=True)
df['call'].replace({'Yes':'Y', 'No':'N', 'No Dont':'N', 'yes':'Y', 'Na':'N'},inplace=True)
df.currloc.replace({'Chennai':'C','Gurgaon':'G','Bangalore':'B','Hyderabad':'H','Delhi':'D','chennai':'C','- Cochin- ':'K','Noida':'N','CHENNAI':'C','chennai ':'C'},inplace=True)
df.venue.replace({'Hosur':'H', 'Gurgaon':'G', 'Bangalore':'B', 'Chennai':'C', 'Hyderabad':'H',
       '- Cochin- ':'K', 'Noida':'N'},inplace=True)
df.jobloc.replace({'Hosur':'H', 'Bangalore':'B', 'Chennai':"C", 'Gurgaon':'G', 'Visakapatinam':'V',
       '- Cochin- ':'K', 'Noida':'N'},inplace=True)
df.drop('id',axis=1,inplace=True)
df['type'].replace({'Scheduled Walkin':'SW', 'Scheduled ':'S', 'Walkin':'W', 'Scheduled Walk In':'SW',
       'Walkin ':'W'},inplace=True)
df.location.replace({'Chennai':'C', 'Gurgaon':'G', 'Bangalore':'B', 'Hyderabad':'H', 'Gurgaonr':'G',
       'Delhi':'D', 'chennai':'C', '- Cochin- ':'K', 'Noida':'N', 'CHENNAI':'C', 'chennai ':'C'},inplace=True)

In [9]:
df.head()

date client industry location            closedpos   skills type  \
0  2015-02-13      H        P        C  Production- Sterile  Routine   SW   
1  2015-02-13      H        P        C  Production- Sterile  Routine   SW   
3  2015-02-13      H        P        C  Production- Sterile  Routine   SW   
4  2015-02-13      H        P        C  Production- Sterile  Routine   SW   
5  2015-02-13      A        I        G     Selenium testing  Routine   SW   

  gender currloc jobloc   ...    permit meeting call no. resume clear letter  \
0   Male       C      H   ...         Y       Y    Y   Y      Y     Y      Y   
1   Male       C      B   ...         Y       Y    Y   Y      Y     Y      Y   
3   Male       C      C   ...         Y       Y    N   Y      N     Y      Y   
4   Male       C      B   ...         Y       Y    Y   N      Y     Y      Y   
5   Male       G      G   ...         Y       Y    Y   Y      Y     Y      Y   

  expat obsat    marit  
0     Y     N   Single  
1     Y     N   Single  
3     N     N   Single  
4     N     N  Married  
5     Y     Y   Single  

[5 rows x 22 columns]

In [10]:
df.closedpos.replace({'Production- Sterile':'P','Selenium testing':'S','Dot Net':'D','AML':'A','Trade Finance':'T','Routine':'R','Niche':'N'},inplace=True)

In [11]:
df.head()

date client industry location closedpos   skills type gender currloc  \
0  2015-02-13      H        P        C         P  Routine   SW   Male       C   
1  2015-02-13      H        P        C         P  Routine   SW   Male       C   
3  2015-02-13      H        P        C         P  Routine   SW   Male       C   
4  2015-02-13      H        P        C         P  Routine   SW   Male       C   
5  2015-02-13      A        I        G         S  Routine   SW   Male       G   

  jobloc   ...    permit meeting call no. resume clear letter expat obsat  \
0      H   ...         Y       Y    Y   Y      Y     Y      Y     Y     N   
1      B   ...         Y       Y    Y   Y      Y     Y      Y     Y     N   
3      C   ...         Y       Y    N   Y      N     Y      Y     N     N   
4      B   ...         Y       Y    Y   N      Y     Y      Y     N     N   
5      G   ...         Y       Y    Y   Y      Y     Y      Y     Y     Y   

     marit  
0   Single  
1   Single  
3   Single  
4  Married  
5   Single  

[5 rows x 22 columns]

In [12]:
df=pd.concat([df,pd.get_dummies(df['client'],prefix='cl_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['industry'],prefix='ind_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['location'],prefix='loc_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['closedpos'],prefix='clopos_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['type'],prefix='type_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['currloc'],prefix='curr_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['jobloc'],prefix='job_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['marit'],prefix='mar_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['gender'],prefix='gen_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['permit'],prefix='per_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['meeting'],prefix='meet_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['call'],prefix='call_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['no.'],prefix='no_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['resume'],prefix='res_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['clear'],prefix='clear_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['letter'],prefix='let_',drop_first=True)],axis=1)
df=pd.concat([df,pd.get_dummies(df['expat'],prefix='exp_',drop_first=True)],axis=1)
df.drop(["marit","gender","permit","meeting","call","no.","resume","clear","letter","expat","currloc"],axis=1,inplace=True)

In [13]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df.loc[:,'obsat']=le.fit_transform(df.loc[:,'obsat'])


In [14]:
df.columns

Index([u'date', u'client', u'industry', u'location', u'closedpos', u'skills',
       u'type', u'jobloc', u'venue', u'natloc', u'obsat', u'cl__A1', u'cl__As',
       u'cl__B', u'cl__F', u'cl__H', u'cl__P', u'cl__P1', u'cl__S', u'cl__U',
       u'cl__W', u'cl__Wb', u'ind__E', u'ind__I', u'ind__P', u'loc__C',
       u'loc__D', u'loc__G', u'loc__H', u'loc__K', u'loc__N', u'clopos__D',
       u'clopos__N', u'clopos__P', u'clopos__R', u'clopos__S', u'clopos__T',
       u'type__SW', u'type__W', u'curr__C', u'curr__D', u'curr__G', u'curr__H',
       u'curr__K', u'curr__N', u'job__C', u'job__G', u'job__H', u'job__K',
       u'job__N', u'job__V', u'mar__Single', u'gen__Male', u'per__Y',
       u'meet__Y', u'call__Y', u'no__Y', u'res__Y', u'clear__Y', u'let__Y',
       u'exp__Y'],
      dtype='object')

In [15]:
df.drop(["client","industry"],axis=1,inplace=True)

In [16]:
df.drop(["location","closedpos","skills","type","jobloc"],axis=1,inplace=True)

In [17]:
print(df.columns)

Index([u'date', u'venue', u'natloc', u'obsat', u'cl__A1', u'cl__As', u'cl__B',
       u'cl__F', u'cl__H', u'cl__P', u'cl__P1', u'cl__S', u'cl__U', u'cl__W',
       u'cl__Wb', u'ind__E', u'ind__I', u'ind__P', u'loc__C', u'loc__D',
       u'loc__G', u'loc__H', u'loc__K', u'loc__N', u'clopos__D', u'clopos__N',
       u'clopos__P', u'clopos__R', u'clopos__S', u'clopos__T', u'type__SW',
       u'type__W', u'curr__C', u'curr__D', u'curr__G', u'curr__H', u'curr__K',
       u'curr__N', u'job__C', u'job__G', u'job__H', u'job__K', u'job__N',
       u'job__V', u'mar__Single', u'gen__Male', u'per__Y', u'meet__Y',
       u'call__Y', u'no__Y', u'res__Y', u'clear__Y', u'let__Y', u'exp__Y'],
      dtype='object')


In [18]:
df=pd.concat([df,pd.get_dummies(df['venue'],prefix='ven_',drop_first=True)],axis=1)
df.drop("venue",axis=1,inplace=True)

In [56]:
for i in df.columns:
    print (i,df[i].unique)

('date', <bound method Series.unique of 0       2015-02-13
1       2015-02-13
3       2015-02-13
4       2015-02-13
5       2015-02-13
6       2015-02-13
7       2015-02-13
8       2015-02-13
9       2015-02-13
10      2015-06-19
11      2015-06-19
12      2015-06-19
13      2015-06-19
14      2015-06-19
15      2015-06-19
16      2015-06-19
17      2015-06-19
18      2015-06-19
19      2015-06-19
20      2015-06-19
21      2015-06-19
22      2015-06-19
23      2015-06-19
24      2015-06-19
25      2015-06-19
26      2015-06-19
27      2015-06-19
28      2015-06-23
29      2015-06-23
30      2015-06-23
           ...    
1202    2016-01-30
1203    2016-01-30
1204    2016-01-30
1205    2016-01-30
1206    2016-01-30
1207    2016-01-30
1208    2016-01-30
1209    2016-01-30
1210    2016-01-30
1211    2016-01-30
1212    2016-01-30
1213    2016-01-30
1214    2016-01-30
1215    2016-01-30
1216    2016-01-30
1217    2016-05-07
1218    2016-05-07
1219    2016-05-07
1220    2016-05-07
1221    20

In [57]:
df.drop("natloc",axis=1,inplace=True)
df.drop("date",axis=1,inplace=True)
df1=df.copy(deep=True)
c_1=0
c_0=0
for i,series in df.iterrows():
    if series["obsat"]==1:
        if c_1<300:
            c_1+=1
        else:
            df1.drop(i,axis=0,inplace=True)
    else:
        if c_0<308:
            c_0+=1

In [20]:
X=df1.drop("obsat",axis=1)

In [21]:
y=df1["obsat"]


# LogisticRegression(0.75,0.72)


In [127]:
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn import linear_model
model=linear_model.LogisticRegression()


In [128]:
model.fit(Xtrain,ytrain)
pred_train=model.predict(Xtrain)
pred_test=model.predict(Xtest)
import sklearn
print(sklearn.metrics.classification_report(ytest,pred_test))

              precision    recall  f1-score   support

           0       0.67      0.76      0.71        75
           1       0.73      0.64      0.68        77

   micro avg       0.70      0.70      0.70       152
   macro avg       0.70      0.70      0.70       152
weighted avg       0.70      0.70      0.70       152



C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [129]:
from sklearn.metrics import average_precision_score
average_precision_score(ytest,model.predict_proba(Xtest)[:,1])

0.75210963742558601

In [130]:
average_precision_score(ytrain,model.predict_proba(Xtrain)[:,1])

0.77898823788995863

In [131]:
Xtrain.shape

(456, 49)

In [132]:
ytrain.shape

(456,)

In [133]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X,y)
print (pd.DataFrame(rf.feature_importances_,index=X.columns,columns=["imp"]).sort_values("imp",ascending=False))


                  imp
exp__Y       0.109450
gen__Male    0.096355
loc__C       0.088446
ven__C       0.075776
mar__Single  0.071967
clopos__R    0.063558
per__Y       0.056229
clopos__N    0.042952
type__SW     0.036117
res__Y       0.034513
let__Y       0.032793
job__C       0.030984
type__W      0.024679
loc__H       0.022139
cl__H        0.017543
ind__P       0.016929
call__Y      0.016009
no__Y        0.015149
cl__S        0.015113
clopos__T    0.012899
clear__Y     0.012431
meet__Y      0.011478
ven__H       0.010347
ind__E       0.009694
cl__P        0.008910
job__V       0.007776
cl__As       0.006613
cl__A1       0.006236
job__K       0.006114
loc__G       0.005659
cl__P1       0.004752
ven__G       0.004660
clopos__P    0.004202
ind__I       0.003642
job__N       0.003180
cl__U        0.002874
job__G       0.002581
clopos__D    0.002255
clopos__S    0.002032
job__H       0.001910
ven__N       0.001333
loc__N       0.000752
loc__D       0.000632
cl__W        0.000337
loc__K    

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [22]:
X=df1[["exp__Y","gen__Male","loc__C","per__Y","ven__C","mar__Single","let__Y","type__W","cl__P"]]
y=df1["obsat"]

In [135]:
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn import linear_model
model=linear_model.LogisticRegression()
model.fit(Xtrain,ytrain)
pred_train=model.predict(Xtrain)
pred_test=model.predict(Xtest)
import sklearn
print(sklearn.metrics.classification_report(ytest,pred_test))
from sklearn.metrics import average_precision_score
print(average_precision_score(ytest,model.predict_proba(Xtest)[:,1]))
print(average_precision_score(ytrain,model.predict_proba(Xtrain)[:,1]))

              precision    recall  f1-score   support

           0       0.67      0.76      0.71        75
           1       0.73      0.64      0.68        77

   micro avg       0.70      0.70      0.70       152
   macro avg       0.70      0.70      0.70       152
weighted avg       0.70      0.70      0.70       152

0.752109637426
0.77898823789


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


# BernoulliNB

In [101]:
from sklearn.naive_bayes import BernoulliNB
gnb=BernoulliNB()
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
gnb.fit(Xtrain,ytrain)


BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [102]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,gnb.predict(Xtrain)))
print (classification_report(ytest,gnb.predict(Xtest)))
print(confusion_matrix(ytrain,gnb.predict(Xtrain)))
print(confusion_matrix(ytest,gnb.predict(Xtest)))
print(accuracy_score(ytest,gnb.predict(Xtest)))

              precision    recall  f1-score   support

           0       0.65      0.81      0.72       233
           1       0.73      0.53      0.62       223

   micro avg       0.68      0.68      0.68       456
   macro avg       0.69      0.67      0.67       456
weighted avg       0.69      0.68      0.67       456

              precision    recall  f1-score   support

           0       0.67      0.80      0.73        75
           1       0.76      0.61      0.68        77

   micro avg       0.70      0.70      0.70       152
   macro avg       0.71      0.71      0.70       152
weighted avg       0.71      0.70      0.70       152

[[189  44]
 [104 119]]
[[60 15]
 [30 47]]
0.703947368421


In [103]:
average_precision_score(ytest,gnb.predict(Xtest))

0.66008312570282013

In [104]:
average_precision_score(ytrain,gnb.predict(Xtrain))

0.6176544831224392

In [48]:
from sklearn import neighbors
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.15,random_state=42)
model=neighbors.KNeighborsRegressor(n_neighbors=11)
model.fit(Xtrain,ytrain)
prediction=model.predict(Xtest)

In [49]:
print (classification_report(ytrain,model.predict(Xtrain)))
print (classification_report(ytest,prediction))
print(confusion_matrix(ytrain,model.predict(Xtrain)))
print(confusion_matrix(ytest,prediction))
print(accuracy_score(ytest,prediction))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

# Random

In [136]:
X=df1[["exp__Y","gen__Male","loc__C","per__Y","ven__C","mar__Single","let__Y","curr__C","type__W","cl__P"]]
y=df1["obsat"]
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.25,random_state=42)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(criterion="entropy")
rfc.fit(Xtrain,ytrain)
prediction=rfc.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,rfc.predict(Xtrain)))
print (classification_report(ytest,prediction))
print(confusion_matrix(ytrain,rfc.predict(Xtrain)))
print(confusion_matrix(ytest,rfc.predict(Xtest)))
print(accuracy_score(ytest,prediction))

KeyError: "['curr__C'] not in index"

In [137]:
average_precision_score(ytest,rfc.predict(Xtest))

ValueError: Number of features of the model must match the input. Model n_features is 10 and input n_features is 49 

In [138]:
average_precision_score(ytrain,rfc.predict(Xtrain))

ValueError: Number of features of the model must match the input. Model n_features is 10 and input n_features is 49 

In [85]:
X1=df.drop("obsat",axis=1)
y1=df["obsat"]

In [86]:
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X1,y1,test_size=0.25,random_state=42)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(criterion="entropy")
rfc.fit(Xtrain,ytrain)
prediction=rfc.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,rfc.predict(Xtrain)))
print (classification_report(ytest,prediction))
print(confusion_matrix(ytrain,rfc.predict(Xtrain)))
print(confusion_matrix(ytest,rfc.predict(Xtest)))
print(accuracy_score(ytest,prediction))

              precision    recall  f1-score   support

           0       0.87      0.31      0.46       231
           1       0.76      0.98      0.85       507

   micro avg       0.77      0.77      0.77       738
   macro avg       0.81      0.64      0.66       738
weighted avg       0.79      0.77      0.73       738

              precision    recall  f1-score   support

           0       0.70      0.30      0.42        77
           1       0.75      0.94      0.83       169

   micro avg       0.74      0.74      0.74       246
   macro avg       0.72      0.62      0.63       246
weighted avg       0.73      0.74      0.70       246

[[ 72 159]
 [ 11 496]]
[[ 23  54]
 [ 10 159]]
0.739837398374


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [88]:
average_precision_score(ytest,rfc.predict(Xtest))

0.7429589322145409

In [89]:
average_precision_score(ytrain,rfc.predict(Xtrain))

0.75572752886388794

In [79]:
X=df[["exp__Y","gen__Male","loc__C","per__Y","ven__C","mar__Single","let__Y","curr__C","type__W","cl__P"]]
y=df["obsat"]
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X1,y1,test_size=0.25,random_state=42)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(criterion="entropy")
rfc.fit(Xtrain,ytrain)
prediction=rfc.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print (classification_report(ytrain,rfc.predict(Xtrain)))
print (classification_report(ytest,prediction))
print(confusion_matrix(ytrain,rfc.predict(Xtrain)))
print(confusion_matrix(ytest,rfc.predict(Xtest)))
print(accuracy_score(ytest,prediction))

              precision    recall  f1-score   support

           0       0.85      0.33      0.47       231
           1       0.76      0.97      0.85       507

   micro avg       0.77      0.77      0.77       738
   macro avg       0.81      0.65      0.66       738
weighted avg       0.79      0.77      0.74       738

              precision    recall  f1-score   support

           0       0.65      0.29      0.40        77
           1       0.74      0.93      0.82       169

   micro avg       0.73      0.73      0.73       246
   macro avg       0.69      0.61      0.61       246
weighted avg       0.71      0.73      0.69       246

[[ 76 155]
 [ 13 494]]
[[ 22  55]
 [ 12 157]]
0.727642276423


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [83]:
average_precision_score(ytest,rfc.predict(Xtest))

0.73676195481392126

In [84]:
average_precision_score(ytrain,rfc.predict(Xtrain))

0.75926900255135066

# XgBoost taking full dataset considering 10 features(0.7327138158815502,0.7419118497917747)

In [60]:
X=df[["exp__Y","gen__Male","loc__C","per__Y","ven__C","mar__Single","let__Y","curr__C","type__W","cl__P"]]
y=df["obsat"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)
import xgboost
classifier = xgboost.XGBClassifier()
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print (cm)
print (classification_report(y_train,classifier.predict(X_train)))
print (classification_report(y_test,classifier.predict(X_test)))
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())


[[ 20  57]
 [  4 165]]
              precision    recall  f1-score   support

           0       0.82      0.22      0.35       231
           1       0.73      0.98      0.84       507

   micro avg       0.74      0.74      0.74       738
   macro avg       0.78      0.60      0.59       738
weighted avg       0.76      0.74      0.69       738

              precision    recall  f1-score   support

           0       0.83      0.26      0.40        77
           1       0.74      0.98      0.84       169

   micro avg       0.75      0.75      0.75       246
   macro avg       0.79      0.62      0.62       246
weighted avg       0.77      0.75      0.70       246

0.724870788596816
0.040031409491194124


In [25]:
df.columns


Index([u'natloc', u'obsat', u'cl__A1', u'cl__As', u'cl__B', u'cl__F', u'cl__H',
       u'cl__P', u'cl__P1', u'cl__S', u'cl__U', u'cl__W', u'cl__Wb', u'ind__E',
       u'ind__I', u'ind__P', u'loc__C', u'loc__D', u'loc__G', u'loc__H',
       u'loc__K', u'loc__N', u'clopos__D', u'clopos__N', u'clopos__P',
       u'clopos__R', u'clopos__S', u'clopos__T', u'type__SW', u'type__W',
       u'job__C', u'job__G', u'job__H', u'job__K', u'job__N', u'job__V',
       u'mar__Single', u'gen__Male', u'per__Y', u'meet__Y', u'call__Y',
       u'no__Y', u'res__Y', u'clear__Y', u'let__Y', u'exp__Y', u'ven__C',
       u'ven__G', u'ven__H', u'ven__K', u'ven__N'],
      dtype='object')

In [62]:
from sklearn.metrics import average_precision_score
print(average_precision_score(y_test,classifier.predict(X_test)))
print(average_precision_score(y_train,classifier.predict(X_train)))

0.7419118497917747
0.7327138158815502


# XGBoost with all data all features(0.7490029686840477,0.7370699740836727)

In [64]:
X1=df.drop(["obsat","natloc"],axis=1)
y1=df["obsat"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size = 0.25, random_state = 42)
import xgboost
classifier = xgboost.XGBClassifier()
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print (cm)
print (classification_report(y_train,classifier.predict(X_train)))
print (classification_report(y_test,classifier.predict(X_test)))
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

[[ 21  56]
 [  5 164]]
              precision    recall  f1-score   support

           0       0.86      0.29      0.43       231
           1       0.75      0.98      0.85       507

   micro avg       0.76      0.76      0.76       738
   macro avg       0.80      0.63      0.64       738
weighted avg       0.78      0.76      0.72       738

              precision    recall  f1-score   support

           0       0.81      0.27      0.41        77
           1       0.75      0.97      0.84       169

   micro avg       0.75      0.75      0.75       246
   macro avg       0.78      0.62      0.63       246
weighted avg       0.76      0.75      0.71       246

0.7370699740836727
0.0400841817753073


In [65]:
from sklearn.metrics import average_precision_score
print(average_precision_score(y_test,classifier.predict(X_test)))
print(average_precision_score(y_train,classifier.predict(X_train)))

0.7437248804978637
0.7490029686840477


#  XGBoost Balanced data all features(0.6733715846994536,0.7217467157161608)

In [78]:
Xtrain=df.copy(deep=True)


In [99]:
df.drop("natloc",axis=1,inplace=True)
df.drop("date",axis=1,inplace=True)
Xtrain=df.copy(deep=True)
c_1=0
c_0=0
for i,series in df.iterrows():
    if series["obsat"]==1:
        if c_1<300:
            c_1+=1
        else:
            Xtrain.drop(i,axis=0,inplace=True)
    else:
        if c_0<308:
            c_0+=1

In [100]:
Xtrain.shape

(608, 56)

In [101]:
df.shape

(984, 56)

In [102]:
(Xtrain.obsat==1).sum()

300

In [103]:
ytrain=Xtrain["obsat"]
Xtrain=Xtrain.drop("obsat",axis=1)
A,Xtest,B,ytest=train_test_split(df.drop("obsat",axis=1),y,test_size=0.25,random_state=42)
print(Xtrain.shape,Xtest.shape,ytrain.shape,ytest.shape)

((608, 55), (246, 55), (608L,), (246L,))


In [105]:
import xgboost
classifier = xgboost.XGBClassifier()
classifier.fit(Xtrain, ytrain)
y_pred=classifier.predict(Xtest)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm = confusion_matrix(ytest, y_pred)
print (cm)
print (classification_report(ytrain,classifier.predict(Xtrain)))
print (classification_report(ytest,classifier.predict(Xtest)))
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = Xtrain, y = ytrain, cv = 10)
print(accuracies.mean())
print(accuracies.std())

[[54 23]
 [94 75]]
              precision    recall  f1-score   support

           0       0.75      0.74      0.74       308
           1       0.73      0.75      0.74       300

   micro avg       0.74      0.74      0.74       608
   macro avg       0.74      0.74      0.74       608
weighted avg       0.74      0.74      0.74       608

              precision    recall  f1-score   support

           0       0.36      0.70      0.48        77
           1       0.77      0.44      0.56       169

   micro avg       0.52      0.52      0.52       246
   macro avg       0.57      0.57      0.52       246
weighted avg       0.64      0.52      0.54       246

0.635
0.21314061948964835


In [106]:
from sklearn.metrics import average_precision_score
print(average_precision_score(ytest,classifier.predict(Xtest)))
print(average_precision_score(ytrain,classifier.predict(Xtrain)))

0.7217467157161608
0.6733715846994536


# XGBoost balanced data 10 features(0.6581172111312764,0.7183160804173937)


In [107]:
X=df[["exp__Y","gen__Male","loc__C","per__Y","ven__C","mar__Single","let__Y","curr__C","type__W","cl__P","obsat"]]
y=df["obsat"]
Xtrain=X.copy(deep=True)
c_1=0
c_0=0
for i,series in X.iterrows():
    if series["obsat"]==1:
        if c_1<300:
            c_1+=1
        else:
            Xtrain.drop(i,axis=0,inplace=True)
    else:
        if c_0<308:
            c_0+=1
ytain=Xtrain.drop("obsat",axis=1)
Xtrain.drop("obsat",axis=1,inplace=True)
X.drop("obsat",axis=1,inplace=True)

C:\Users\Dell\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [109]:
A,Xtest,B,ytest=train_test_split(X,y,test_size=0.25,random_state=42)
print(Xtrain.shape,Xtest.shape,ytrain.shape,ytest.shape)

((608, 10), (246, 10), (608L,), (246L,))


In [110]:
import xgboost
classifier = xgboost.XGBClassifier()
classifier.fit(Xtrain, ytrain)
y_pred=classifier.predict(Xtest)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm = confusion_matrix(ytest, y_pred)
print (cm)
print (classification_report(ytrain,classifier.predict(Xtrain)))
print (classification_report(ytest,classifier.predict(Xtest)))
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = Xtrain, y = ytrain, cv = 10)
print(accuracies.mean())
print(accuracies.std())

[[53 24]
 [94 75]]
              precision    recall  f1-score   support

           0       0.72      0.74      0.73       308
           1       0.73      0.70      0.72       300

   micro avg       0.72      0.72      0.72       608
   macro avg       0.72      0.72      0.72       608
weighted avg       0.72      0.72      0.72       608

              precision    recall  f1-score   support

           0       0.36      0.69      0.47        77
           1       0.76      0.44      0.56       169

   micro avg       0.52      0.52      0.52       246
   macro avg       0.56      0.57      0.52       246
weighted avg       0.63      0.52      0.53       246

0.6497540983606558
0.1663708945035398


In [111]:
from sklearn.metrics import average_precision_score
print(average_precision_score(ytest,classifier.predict(Xtest)))
print(average_precision_score(ytrain,classifier.predict(Xtrain)))

0.7183160804173937
0.6581172111312764
