In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
from sklearn import linear_model
from sklearn import preprocessing
from sklearn import model_selection
from sklearn import tree
from sklearn import ensemble
from sklearn import utils

In [15]:
df=pd.read_csv('D:/datasets/iris.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepallength    150 non-null float64
sepalwidth     150 non-null float64
petallength    150 non-null float64
petalwidth     150 non-null float64
class          150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [5]:
df[:5]

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [16]:
#all X are continuous
#GaussianNB
from sklearn import naive_bayes
df=utils.shuffle(df)

In [18]:
#df["type"]=(df["class"]=="Iris-setosa").astype(np.int)
df.drop("class",axis=1,inplace=True)

In [19]:
X=df.drop("type",axis=1)
print(df.head())
print(X.head())

     sepallength  sepalwidth  petallength  petalwidth  type
66           5.6         3.0          4.5         1.5     2
32           5.2         4.1          1.5         0.1     1
146          6.3         2.5          5.0         1.9     3
128          6.4         2.8          5.6         2.1     3
112          6.8         3.0          5.5         2.1     3
     sepallength  sepalwidth  petallength  petalwidth
66           5.6         3.0          4.5         1.5
32           5.2         4.1          1.5         0.1
146          6.3         2.5          5.0         1.9
128          6.4         2.8          5.6         2.1
112          6.8         3.0          5.5         2.1


In [20]:
y=df["type"]
Xtrain,Xtest,ytrain,ytest=model_selection.train_test_split(X,y,test_size=0.15,random_state=42)
model=()
model.fit(Xtrain,ytrain)

GaussianNB(priors=None)

In [21]:
from sklearn import metrics
prediction=model.predict(Xtest)
print("Confusion Matrix :",metrics.confusion_matrix(ytest,prediction))

Confusion Matrix : [[8 0 0]
 [0 7 0]
 [0 1 7]]


In [22]:
print("Confusion Matrix :",metrics.confusion_matrix(ytrain,model.predict(Xtrain)))

Confusion Matrix : [[42  0  0]
 [ 0 40  3]
 [ 0  3 39]]


In [23]:
probs=model.predict_proba(Xtest)

In [24]:
probs

array([[1.00000000e+000, 6.18703138e-017, 4.03069777e-025],
       [1.00000000e+000, 1.38039958e-015, 7.36558837e-024],
       [2.08164895e-065, 9.99952713e-001, 4.72867118e-005],
       [2.85343449e-106, 6.39938834e-001, 3.60061166e-001],
       [1.00000000e+000, 4.81772944e-015, 5.47083105e-023],
       [8.62192754e-121, 7.03494869e-001, 2.96505131e-001],
       [1.28340780e-054, 9.99990006e-001, 9.99353429e-006],
       [1.00000000e+000, 2.49639444e-017, 6.60910101e-025],
       [7.76673049e-087, 9.85084017e-001, 1.49159833e-002],
       [6.11336255e-205, 2.10762763e-006, 9.99997892e-001],
       [1.00000000e+000, 3.27942068e-018, 1.26797165e-025],
       [1.00000000e+000, 2.11182236e-017, 1.95118849e-025],
       [1.00000000e+000, 6.18703138e-017, 4.03069777e-025],
       [5.48524214e-205, 3.08763852e-008, 9.99999969e-001],
       [2.52781130e-173, 9.09863513e-007, 9.99999090e-001],
       [8.72270857e-104, 7.85393674e-001, 2.14606326e-001],
       [5.84044288e-068, 9.99708815e-001

In [17]:
df["type"]=df["class"].replace({"Iris-setosa":1,"Iris-versicolor":2,"Iris-virginica":3})